### ISSUE TITLE
Roscore Status Notification

### ISSUE THREAD

**Issue by AWatk** [rosmod/rosmct#1]
Notification to server of the addition/removal of a roscore (and therefore a ros deployment)

Notification Object:

```node.js
{
  name: SYSTEM_NAME,
  master_uri: ROS_MASTER_URI,
  status: OPEN/CLOSE
}
```

**Comment by AWatk** [comment]
updated to instead be the notification of a rosbridge server instead of roscore, since rosbridge will be handled by rosmod https://github.com/rosmod/webgme-rosmod/issues/186

```node.js
{
 name: SYSTEM_NAME,
 rosbridgeurl: ROSBRIDGE_URL,
 rosbridgeport: ROSBRIDGE_PORT,
 status: OPEN/CLOSE
}

**Comment by AWatk** [comment]
notification is set on startup and teardown

**Comment by AWatk** [comment]
websocket address `ws://localhost:8085/realtime/notify`

**Comment by finger563** [comment]
using this for reference: https://github.com/websockets/ws
